### ISSUE TITLE
Improvement list on front

### ISSUE THREAD

**Issue by marumero4241** [kensei416/todo-app-v2#7]
## Task list

- [x] Use Nightwatch to test on front. https://github.com/kensei416/rails-vue-todo/pull/8 https://github.com/kensei416/rails-vue-todo/pull/9

- [ ] fix circle ci config for doing nightwatch on circle ci https://github.com/kensei416/rails-vue-todo/pull/11

- [ ] frontのコードが書き換わったので、新たにunit test を書き直す
  ## test list 
   - [x] login form validate check   https://github.com/kensei416/todo-app-v2/pull/10
   - [ ] logout form validate check 
   - [ ] login, logout ajax mock test
   - [ ] app add,delete category test
   - [ ] task, add, delete test
